<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DELL" name="com.w2a.archBatch2.Rough.TestCase2" tests="1" failures="0" timestamp="11 Mar 2018 08:27:23 GMT" time="0.000" errors="1">
  <testcase name="validateUploadProfilePicture" time="0.000" classname="com.w2a.archBatch2.Rough.TestCase2">
    <error type="org.testng.TestNGException" message="
Method public static void com.w2a.archBatch2.Rough.TestCase2.validateUploadProfilePicture(java.lang.String,java.lang.String) requires a @DataProvider named : getData">
      <![CDATA[org.testng.TestNGException: 
Method public static void com.w2a.archBatch2.Rough.TestCase2.validateUploadProfilePicture(java.lang.String,java.lang.String) requires a @DataProvider named : getData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- validateUploadProfilePicture -->
</testsuite> <!-- com.w2a.archBatch2.Rough.TestCase2 -->
