<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DELL" name="com.w2a.archBatch2.TestCases.ValidateFacebookLogin" tests="2" failures="0" timestamp="24 Mar 2018 06:12:14 GMT" time="35.684" errors="2">
  <testcase name="validateFBLoginWIthValidCred" time="15.966" classname="com.w2a.archBatch2.TestCases.ValidateFacebookLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.w2a.archBatch2.PageObjects.BasePage.waitForPageLoad(BasePage.java:35)
	at com.w2a.archBatch2.PageObjects.BasePage.openPage(BasePage.java:27)
	at com.w2a.archBatch2.PageObjects.FacebookLandingPage.doLoginWithValidCredentials(FacebookLandingPage.java:49)
	at com.w2a.archBatch2.TestCases.ValidateFacebookLogin.validateFBLoginWIthValidCred(ValidateFacebookLogin.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- validateFBLoginWIthValidCred -->
  <testcase name="validateFBLoginWIthValidCred" time="19.718" classname="com.w2a.archBatch2.TestCases.ValidateFacebookLogin">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.w2a.archBatch2.PageObjects.BasePage.waitForPageLoad(BasePage.java:35)
	at com.w2a.archBatch2.PageObjects.BasePage.openPage(BasePage.java:27)
	at com.w2a.archBatch2.PageObjects.FacebookLandingPage.doLoginWithValidCredentials(FacebookLandingPage.java:49)
	at com.w2a.archBatch2.TestCases.ValidateFacebookLogin.validateFBLoginWIthValidCred(ValidateFacebookLogin.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- validateFBLoginWIthValidCred -->
</testsuite> <!-- com.w2a.archBatch2.TestCases.ValidateFacebookLogin -->
